/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Portfolio4.glb -o src/components/Portfolio4.tsx -k 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = '01_Run' | '02_walk' | '03_creep' | '04_Idle' | '05_site'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_11: THREE.SkinnedMesh
    Object_12: THREE.SkinnedMesh
    Object_13: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    Cube026: THREE.Mesh
    Cube040: THREE.Mesh
    Plane: THREE.Mesh
    Cube001: THREE.Mesh
    Cube004: THREE.Mesh
    Cube020: THREE.Mesh
    Cube022: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube005: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube021: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    books: THREE.Mesh
    Catcus: THREE.Mesh
    chair: THREE.Mesh
    mouse: THREE.Mesh
    penguin: THREE.Mesh
    ['penguin-wing-0']: THREE.Mesh
    ['penguin-wing-1']: THREE.Mesh
    picture: THREE.Mesh
    picture001: THREE.Mesh
    plant: THREE.Mesh
    plant001: THREE.Mesh
    speaker: THREE.Mesh
    Table_small: THREE.Mesh
    Catcus_leaf: THREE.Mesh
    Cube: THREE.Mesh
    Cube027: THREE.Mesh
    Cube029: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cube006: THREE.Mesh
    Cube028: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Face_new: THREE.Mesh
    Hair: THREE.Mesh
    Hand: THREE.Mesh
    Leg: THREE.Mesh
    Pant: THREE.Mesh
    Shirt: THREE.Mesh
    Curve: THREE.Mesh
    Curve002_1: THREE.Mesh
    Curve002_2: THREE.Mesh
    Curve002: THREE.Mesh
    Curve008_1: THREE.Mesh
    Curve008_2: THREE.Mesh
    Curve008_3: THREE.Mesh
    Curve011_1: THREE.Mesh
    Curve011_2: THREE.Mesh
    Curve011_3: THREE.Mesh
    Curve011_4: THREE.Mesh
    Curve011_5: THREE.Mesh
    Curve011_6: THREE.Mesh
    Curve011_7: THREE.Mesh
    Curve011_8: THREE.Mesh
    Curve011_9: THREE.Mesh
    Curve011_10: THREE.Mesh
    Curve011_11: THREE.Mesh
    Curve011_12: THREE.Mesh
    Curve011_13: THREE.Mesh
    Curve011_14: THREE.Mesh
    Curve011_15: THREE.Mesh
    Curve011_16: THREE.Mesh
    Curve011_17: THREE.Mesh
    Curve011_18: THREE.Mesh
    Curve011_19: THREE.Mesh
    Curve011_20: THREE.Mesh
    Curve011_21: THREE.Mesh
    Curve011_22: THREE.Mesh
    Curve011_23: THREE.Mesh
    Curve011_24: THREE.Mesh
    Curve011_25: THREE.Mesh
    Curve011_26: THREE.Mesh
    Curve011_27: THREE.Mesh
    Curve011_28: THREE.Mesh
    Curve011_29: THREE.Mesh
    Curve011_30: THREE.Mesh
    Curve011_31: THREE.Mesh
    Curve011_32: THREE.Mesh
    Curve011_33: THREE.Mesh
    Curve011_34: THREE.Mesh
    Curve011_35: THREE.Mesh
    Curve011_36: THREE.Mesh
    Curve011_37: THREE.Mesh
    Curve011_38: THREE.Mesh
    Curve011_39: THREE.Mesh
    Curve275: THREE.Mesh
    Curve275_1: THREE.Mesh
    Curve275_2: THREE.Mesh
    Curve005: THREE.Mesh
    Curve281: THREE.Mesh
    Curve281_1: THREE.Mesh
    Curve281_2: THREE.Mesh
    Curve281_3: THREE.Mesh
    Curve281_4: THREE.Mesh
    Curve291: THREE.Mesh
    Curve291_1: THREE.Mesh
    Curve006: THREE.Mesh
    Curve304: THREE.Mesh
    Curve304_1: THREE.Mesh
    Curve010: THREE.Mesh
    _rootJoint: THREE.Bone
  }
  materials: {
    eyes: THREE.MeshStandardMaterial
    claws: THREE.MeshStandardMaterial
    teeth__nor2_tga: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['SVGMat.001']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['SVGMat.009']: THREE.MeshStandardMaterial
    ['SVGMat.010']: THREE.MeshStandardMaterial
    ['SVGMat.011']: THREE.MeshStandardMaterial
    ['SVGMat.013']: THREE.MeshStandardMaterial
    ['SVGMat.014']: THREE.MeshStandardMaterial
    ['SVGMat.015']: THREE.MeshStandardMaterial
    ['SVGMat.016']: THREE.MeshStandardMaterial
    ['SVGMat.017']: THREE.MeshStandardMaterial
    ['SVGMat.018']: THREE.MeshStandardMaterial
    ['SVGMat.019']: THREE.MeshStandardMaterial
    ['SVGMat.020']: THREE.MeshStandardMaterial
    ['SVGMat.021']: THREE.MeshStandardMaterial
    ['SVGMat.022']: THREE.MeshStandardMaterial
    ['SVGMat.023']: THREE.MeshStandardMaterial
    ['SVGMat.024']: THREE.MeshStandardMaterial
    ['SVGMat.025']: THREE.MeshStandardMaterial
    ['SVGMat.026']: THREE.MeshStandardMaterial
    ['SVGMat.027']: THREE.MeshStandardMaterial
    ['SVGMat.028']: THREE.MeshStandardMaterial
    ['SVGMat.029']: THREE.MeshStandardMaterial
    ['SVGMat.030']: THREE.MeshStandardMaterial
    ['SVGMat.031']: THREE.MeshStandardMaterial
    ['SVGMat.032']: THREE.MeshStandardMaterial
    ['SVGMat.033']: THREE.MeshStandardMaterial
    ['SVGMat.034']: THREE.MeshStandardMaterial
    ['SVGMat.035']: THREE.MeshStandardMaterial
    ['SVGMat.036']: THREE.MeshStandardMaterial
    ['SVGMat.037']: THREE.MeshStandardMaterial
    ['SVGMat.038']: THREE.MeshStandardMaterial
    ['SVGMat.039']: THREE.MeshStandardMaterial
    ['SVGMat.040']: THREE.MeshStandardMaterial
    ['SVGMat.041']: THREE.MeshStandardMaterial
    ['SVGMat.042']: THREE.MeshStandardMaterial
    ['SVGMat.043']: THREE.MeshStandardMaterial
    ['SVGMat.044']: THREE.MeshStandardMaterial
    ['SVGMat.045']: THREE.MeshStandardMaterial
    ['SVGMat.046']: THREE.MeshStandardMaterial
    ['SVGMat.047']: THREE.MeshStandardMaterial
    ['SVGMat.048']: THREE.MeshStandardMaterial
    ['SVGMat.049']: THREE.MeshStandardMaterial
    ['SVGMat.050']: THREE.MeshStandardMaterial
    ['SVGMat.051']: THREE.MeshStandardMaterial
    ['SVGMat.055']: THREE.MeshStandardMaterial
    ['SVGMat.053']: THREE.MeshStandardMaterial
    ['SVGMat.054']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['SVGMat.060']: THREE.MeshStandardMaterial
    ['SVGMat.058']: THREE.MeshStandardMaterial
    ['SVGMat.059']: THREE.MeshStandardMaterial
    ['SVGMat.061']: THREE.MeshStandardMaterial
    ['SVGMat.062']: THREE.MeshStandardMaterial
    ['SVGMat.066']: THREE.MeshStandardMaterial
    ['SVGMat.068']: THREE.MeshStandardMaterial
    ['SVGMat.075']: THREE.MeshStandardMaterial
    ['SVGMat.077']: THREE.MeshStandardMaterial
    ['SVGMat.078']: THREE.MeshStandardMaterial
    ['SVGMat.079']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/Portfolio4.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[4.295, 0.811, 4.281]} rotation={[-1.742, 0.285, 2.454]} scale={1.977}>
          <group name="e4ef26d3d7a44d328db4b473b35c6be8fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Hemi" position={[-0.85, 1.001, 0.915]} rotation={[0.751, 0.1, 0.083]}>
                    <group name="Object_68" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_69" />
                    </group>
                  </group>
                  <group name="Object_10" position={[0, 0.002, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_6" position={[0, 0.002, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_8" position={[0, 0.002, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Plane001" position={[0, -0.348, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Wolf1" position={[0, 0, 0.002]} />
                  <group name="Wolf2" position={[0, 0, 0.002]} />
                  <group name="Wolf3" position={[0, 0, 0.002]} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.eyes} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.claws} skeleton={nodes.Object_12.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.teeth__nor2_tga} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.001']} skeleton={nodes.Object_9.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Cube025" position={[0, 6.582, 0]} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[0.087, 0, 5.324]} scale={0.304} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={nodes.Cube040.material} position={[-6.863, 3.597, 5.593]} rotation={[0, 1.145, 0]} scale={[0.076, 0.067, 0.183]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Material} position={[-6.863, 3.527, 5.593]} rotation={[-3.11, -1.144, 0.029]} scale={[0.076, 0.068, 0.183]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0, 0, 7.149]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[7.087, 0.814, -2.041]} rotation={[0, 1.219, 0]} scale={0.206} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[0, 3.961, 5.686]} scale={0.23} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[0, 2.043, 5.843]} scale={0.23} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.009']} position={[7.048, 0.664, -1.984]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.014']} position={[7.124, 1.23, -2.215]} rotation={[0, 0.365, 0]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.014']} position={[7.313, 1.238, -0.467]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.002']} position={[-0.019, 0.122, 3.471]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.002']} position={[-2.096, 0.122, -1.017]} rotation={[0, -0.402, 0]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.002']} position={[2.058, 0.122, -1.036]} rotation={[0, 0.402, 0]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.007']} position={[0.044, 1.902, 6.812]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.007']} position={[-1.475, 1.902, 6.749]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.007']} position={[-2.946, 1.902, 6.527]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.007']} position={[-4.401, 1.902, 6.16]} rotation={[0, -0.085, 0]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.007']} position={[-5.801, 1.902, 5.657]} rotation={[0, -0.085, 0]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Material.007']} position={[1.554, 1.902, 6.767]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Material.007']} position={[3.049, 1.902, 6.528]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['Material.007']} position={[4.486, 1.902, 6.137]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['Material.007']} position={[5.88, 1.902, 5.587]} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Material.004']} position={[0, 3.69, 7.153]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['Material.037']} position={[0, 1.772, 7.305]} scale={[1.04, 1, 1]} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[6.673, 1.153, -2.101]} rotation={[0, -0.245, 0]} scale={0.08} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.022']} position={[7.431, 3.606, -1.007]} rotation={[0.003, 0, 0]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.019']} position={[0, 0.519, 0]} rotation={[0, -0.178, 0]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.021']} position={[0, 0.314, 0]} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.020']} position={[0, 0.667, 0]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.015']} position={[7.287, 1.233, -0.466]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.015']} position={[7.083, 1.226, -1.947]} rotation={[-Math.PI, 0.45, Math.PI / 2]} />
        <mesh name="books" geometry={nodes.books.geometry} material={materials['Material.034']} position={[7.486, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} />
        <mesh name="Catcus" geometry={nodes.Catcus.geometry} material={materials['Material.033']} position={[7.486, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} />
        <mesh name="chair" geometry={nodes.chair.geometry} material={materials['Material.010']} position={[5.701, 0.224, -0.663]} rotation={[Math.PI, -0.011, Math.PI]} />
        <mesh name="mouse" geometry={nodes.mouse.geometry} material={materials['Material.013']} position={[6.368, 0.013, 1.149]} rotation={[Math.PI, -0.011, Math.PI]} />
        <mesh name="penguin" geometry={nodes.penguin.geometry} material={nodes.penguin.material} position={[6.303, 0.828, -2.613]} rotation={[Math.PI, -1.186, Math.PI]}>
          <mesh name="penguin-wing-0" geometry={nodes['penguin-wing-0'].geometry} material={nodes['penguin-wing-0'].material} />
          <mesh name="penguin-wing-1" geometry={nodes['penguin-wing-1'].geometry} material={nodes['penguin-wing-1'].material} />
        </mesh>
        <mesh name="picture" geometry={nodes.picture.geometry} material={materials['Material.018']} position={[7.638, 2.13, 0.711]} rotation={[Math.PI, -0.011, Math.PI]} />
        <mesh name="picture001" geometry={nodes.picture001.geometry} material={materials['Material.017']} position={[7.621, 2.165, 0.711]} rotation={[Math.PI, -0.011, Math.PI]} />
        <mesh name="plant" geometry={nodes.plant.geometry} material={materials['Material.016']} position={[6.833, 0.18, 1.463]} rotation={[Math.PI, -0.011, Math.PI]} />
        <mesh name="plant001" geometry={nodes.plant001.geometry} material={materials['Material.011']} position={[6.833, 0.18, 1.463]} rotation={[Math.PI, -0.011, Math.PI]} />
        <mesh name="speaker" geometry={nodes.speaker.geometry} material={nodes.speaker.material} position={[5.844, 0.732, -2.568]} rotation={[0, -1, 0.049]} />
        <mesh name="Table_small" geometry={nodes.Table_small.geometry} material={nodes.Table_small.material} position={[7.486, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} />
        <mesh name="Catcus_leaf" geometry={nodes.Catcus_leaf.geometry} material={materials['Material.032']} position={[7.486, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.038']} position={[0.087, 1.863, 7.487]} scale={[7.081, 1.809, 0.058]} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.Glass} position={[7.692, 1.904, -0.998]} scale={[0.032, 1.856, 6.427]} />
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials['Material.005']} position={[0, 0.038, 0.16]} scale={[7.678, 0.029, 7.648]} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.003']} position={[0, 0.097, -0.056]} scale={[5.607, 0.067, 5.607]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[6.805, 0.753, -0.41]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.17, -0.026, -0.539]} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials['Material.036']} position={[0.042, 1.857, 7.129]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials['Material.036']} position={[-1.547, 1.857, 7.08]} rotation={[0, -0.201, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials['Material.036']} position={[-3.026, 1.857, 6.808]} rotation={[0, -0.375, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['Material.036']} position={[-4.501, 1.857, 6.452]} rotation={[0, -0.395, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials['Material.036']} position={[-5.962, 1.857, 5.961]} rotation={[0, -0.435, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['Material.036']} position={[1.599, 1.857, 7.063]} rotation={[0, 0.038, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['Material.036']} position={[3.094, 1.857, 6.843]} rotation={[0, 0.261, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['Material.036']} position={[4.566, 1.857, 6.454]} rotation={[0, 0.357, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['Material.036']} position={[5.984, 1.857, 5.895]} rotation={[0, 0.361, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['Material.036']} position={[-7.661, 1.857, 5.185]} rotation={[0, -0.435, 0]} scale={[0.047, 1.771, 0.263]} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials.Glass} position={[-7.623, 1.904, -0.998]} rotation={[Math.PI, -0.001, Math.PI]} scale={[0.032, 1.856, 6.427]} />
        <mesh name="Face_new" geometry={nodes.Face_new.geometry} material={materials['Material.030']} position={[5.777, 1.751, 0.932]} rotation={[1.549, -0.036, -2.124]} />
        <mesh name="Hair" geometry={nodes.Hair.geometry} material={materials['Material.027']} position={[5.725, 0.407, 0.964]} rotation={[-Math.PI, 0.94, -Math.PI]} />
        <mesh name="Hand" geometry={nodes.Hand.geometry} material={materials['Material.026']} position={[5.729, 0.322, 0.961]} rotation={[-Math.PI, 0.94, -Math.PI]} />
        <mesh name="Leg" geometry={nodes.Leg.geometry} material={materials['Material.028']} position={[5.722, 0.322, 0.966]} rotation={[-Math.PI, 0.94, -Math.PI]} />
        <mesh name="Pant" geometry={nodes.Pant.geometry} material={materials['Material.025']} position={[5.722, 0.322, 0.966]} rotation={[-Math.PI, 0.94, -Math.PI]} />
        <mesh name="Shirt" geometry={nodes.Shirt.geometry} material={materials['Material.024']} position={[5.722, 0.322, 0.966]} rotation={[-Math.PI, 0.94, -Math.PI]} />
        <mesh name="Curve" geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[3.838, 2.434, 6.611]} rotation={[-1.58, -0.004, 0.434]} />
        <group name="Curve001" position={[-2.178, 2.56, 7.079]} rotation={[1.585, 0.001, -3.139]}>
          <mesh name="Curve002_1" geometry={nodes.Curve002_1.geometry} material={materials['Material.006']} />
          <mesh name="Curve002_2" geometry={nodes.Curve002_2.geometry} material={materials['Material.023']} />
        </group>
        <mesh name="Curve002" geometry={nodes.Curve002.geometry} material={materials['Material.031']} position={[-0.728, 2.526, 7.038]} rotation={[-1.551, 0, 0]} />
        <group name="Curve003" position={[-3.833, 2.53, 6.689]} rotation={[1.568, -0.006, -2.725]}>
          <mesh name="Curve008_1" geometry={nodes.Curve008_1.geometry} material={materials['SVGMat.009']} />
          <mesh name="Curve008_2" geometry={nodes.Curve008_2.geometry} material={materials['SVGMat.010']} />
          <mesh name="Curve008_3" geometry={nodes.Curve008_3.geometry} material={materials['SVGMat.011']} />
        </group>
        <group name="Curve004" position={[-6.78, 0.804, 5.681]} rotation={[1.571, -0.002, -2.743]}>
          <mesh name="Curve011_1" geometry={nodes.Curve011_1.geometry} material={materials['SVGMat.013']} />
          <mesh name="Curve011_2" geometry={nodes.Curve011_2.geometry} material={materials['SVGMat.014']} />
          <mesh name="Curve011_3" geometry={nodes.Curve011_3.geometry} material={materials['SVGMat.015']} />
          <mesh name="Curve011_4" geometry={nodes.Curve011_4.geometry} material={materials['SVGMat.016']} />
          <mesh name="Curve011_5" geometry={nodes.Curve011_5.geometry} material={materials['SVGMat.017']} />
          <mesh name="Curve011_6" geometry={nodes.Curve011_6.geometry} material={materials['SVGMat.018']} />
          <mesh name="Curve011_7" geometry={nodes.Curve011_7.geometry} material={materials['SVGMat.019']} />
          <mesh name="Curve011_8" geometry={nodes.Curve011_8.geometry} material={materials['SVGMat.020']} />
          <mesh name="Curve011_9" geometry={nodes.Curve011_9.geometry} material={materials['SVGMat.021']} />
          <mesh name="Curve011_10" geometry={nodes.Curve011_10.geometry} material={materials['SVGMat.022']} />
          <mesh name="Curve011_11" geometry={nodes.Curve011_11.geometry} material={materials['SVGMat.023']} />
          <mesh name="Curve011_12" geometry={nodes.Curve011_12.geometry} material={materials['SVGMat.024']} />
          <mesh name="Curve011_13" geometry={nodes.Curve011_13.geometry} material={materials['SVGMat.025']} />
          <mesh name="Curve011_14" geometry={nodes.Curve011_14.geometry} material={materials['SVGMat.026']} />
          <mesh name="Curve011_15" geometry={nodes.Curve011_15.geometry} material={materials['SVGMat.027']} />
          <mesh name="Curve011_16" geometry={nodes.Curve011_16.geometry} material={materials['SVGMat.028']} />
          <mesh name="Curve011_17" geometry={nodes.Curve011_17.geometry} material={materials['SVGMat.029']} />
          <mesh name="Curve011_18" geometry={nodes.Curve011_18.geometry} material={materials['SVGMat.030']} />
          <mesh name="Curve011_19" geometry={nodes.Curve011_19.geometry} material={materials['SVGMat.031']} />
          <mesh name="Curve011_20" geometry={nodes.Curve011_20.geometry} material={materials['SVGMat.032']} />
          <mesh name="Curve011_21" geometry={nodes.Curve011_21.geometry} material={materials['SVGMat.033']} />
          <mesh name="Curve011_22" geometry={nodes.Curve011_22.geometry} material={materials['SVGMat.034']} />
          <mesh name="Curve011_23" geometry={nodes.Curve011_23.geometry} material={materials['SVGMat.035']} />
          <mesh name="Curve011_24" geometry={nodes.Curve011_24.geometry} material={materials['SVGMat.036']} />
          <mesh name="Curve011_25" geometry={nodes.Curve011_25.geometry} material={materials['SVGMat.037']} />
          <mesh name="Curve011_26" geometry={nodes.Curve011_26.geometry} material={materials['SVGMat.038']} />
          <mesh name="Curve011_27" geometry={nodes.Curve011_27.geometry} material={materials['SVGMat.039']} />
          <mesh name="Curve011_28" geometry={nodes.Curve011_28.geometry} material={materials['SVGMat.040']} />
          <mesh name="Curve011_29" geometry={nodes.Curve011_29.geometry} material={materials['SVGMat.041']} />
          <mesh name="Curve011_30" geometry={nodes.Curve011_30.geometry} material={materials['SVGMat.042']} />
          <mesh name="Curve011_31" geometry={nodes.Curve011_31.geometry} material={materials['SVGMat.043']} />
          <mesh name="Curve011_32" geometry={nodes.Curve011_32.geometry} material={materials['SVGMat.044']} />
          <mesh name="Curve011_33" geometry={nodes.Curve011_33.geometry} material={materials['SVGMat.045']} />
          <mesh name="Curve011_34" geometry={nodes.Curve011_34.geometry} material={materials['SVGMat.046']} />
          <mesh name="Curve011_35" geometry={nodes.Curve011_35.geometry} material={materials['SVGMat.047']} />
          <mesh name="Curve011_36" geometry={nodes.Curve011_36.geometry} material={materials['SVGMat.048']} />
          <mesh name="Curve011_37" geometry={nodes.Curve011_37.geometry} material={materials['SVGMat.049']} />
          <mesh name="Curve011_38" geometry={nodes.Curve011_38.geometry} material={materials['SVGMat.050']} />
          <mesh name="Curve011_39" geometry={nodes.Curve011_39.geometry} material={materials['SVGMat.051']} />
        </group>
        <group name="Curve007" position={[6.588, 2.439, 5.444]} rotation={[1.58, 0.038, 2.34]}>
          <mesh name="Curve275" geometry={nodes.Curve275.geometry} material={materials['SVGMat.055']} />
          <mesh name="Curve275_1" geometry={nodes.Curve275_1.geometry} material={materials['SVGMat.053']} />
          <mesh name="Curve275_2" geometry={nodes.Curve275_2.geometry} material={materials['SVGMat.054']} />
        </group>
        <mesh name="Curve005" geometry={nodes.Curve005.geometry} material={materials['Material.035']} position={[5.482, 2.376, 6.267]} rotation={[1.567, 0.006, 2.678]} />
        <group name="Curve011" position={[2.334, 2.416, 6.917]} rotation={[1.58, 0.018, 2.792]}>
          <mesh name="Curve281" geometry={nodes.Curve281.geometry} material={materials['SVGMat.060']} />
          <mesh name="Curve281_1" geometry={nodes.Curve281_1.geometry} material={materials['SVGMat.058']} />
          <mesh name="Curve281_2" geometry={nodes.Curve281_2.geometry} material={materials['SVGMat.059']} />
          <mesh name="Curve281_3" geometry={nodes.Curve281_3.geometry} material={materials['SVGMat.061']} />
          <mesh name="Curve281_4" geometry={nodes.Curve281_4.geometry} material={materials['SVGMat.062']} />
        </group>
        <group name="Curve008" position={[1.02, 2.523, 6.909]} rotation={[1.579, 0.004, 2.995]}>
          <mesh name="Curve291" geometry={nodes.Curve291.geometry} material={materials['SVGMat.066']} />
          <mesh name="Curve291_1" geometry={nodes.Curve291_1.geometry} material={materials['SVGMat.068']} />
        </group>
        <mesh name="Curve006" geometry={nodes.Curve006.geometry} material={materials['SVGMat.075']} position={[-5.389, 0.781, 6.397]} rotation={[1.551, 0.124, -3.024]} />
        <group name="Curve009" position={[-5.215, 2.578, 6.324]} rotation={[1.554, 0.016, -2.878]}>
          <mesh name="Curve304" geometry={nodes.Curve304.geometry} material={materials['SVGMat.077']} />
          <mesh name="Curve304_1" geometry={nodes.Curve304_1.geometry} material={materials['SVGMat.078']} />
        </group>
        <mesh name="Curve010" geometry={nodes.Curve010.geometry} material={materials['SVGMat.079']} position={[-6.959, 2.883, 5.636]} rotation={[2.068, -0.544, -2.511]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Portfolio4.glb')
