/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Portfolio1.glb -o src/components/Portfolio1.tsx 
*/
"use client"
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    shelving: THREE.Mesh
    body: THREE.Mesh
    Face: THREE.Mesh
    EM3D_Base_Body: THREE.Mesh
    Cube026: THREE.Mesh
    Cube006: THREE.Mesh
    Cube028: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube001: THREE.Mesh
    Cube004: THREE.Mesh
    Cube020: THREE.Mesh
    Cube022: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube005: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube021: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    books: THREE.Mesh
    Catcus: THREE.Mesh
    chair: THREE.Mesh
    mouse: THREE.Mesh
    penguin: THREE.Mesh
    ['penguin-wing-0']: THREE.Mesh
    ['penguin-wing-1']: THREE.Mesh
    picture: THREE.Mesh
    picture001: THREE.Mesh
    plant: THREE.Mesh
    plant001: THREE.Mesh
    speaker: THREE.Mesh
    Table_small: THREE.Mesh
    Catcus_leaf: THREE.Mesh
    Cube: THREE.Mesh
    Cube027: THREE.Mesh
    Cube029: THREE.Mesh
    Cylinder002: THREE.Mesh
    Face_new: THREE.Mesh
    Hair: THREE.Mesh
    Hand: THREE.Mesh
    Leg: THREE.Mesh
    Pant: THREE.Mesh
    Shirt: THREE.Mesh
    Curve: THREE.Mesh
    Curve002_1: THREE.Mesh
    Curve002_2: THREE.Mesh
    Curve002: THREE.Mesh
    Curve008_1: THREE.Mesh
    Curve008_2: THREE.Mesh
    Curve008_3: THREE.Mesh
    Curve011_1: THREE.Mesh
    Curve011_2: THREE.Mesh
    Curve011_3: THREE.Mesh
    Curve011_4: THREE.Mesh
    Curve011_5: THREE.Mesh
    Curve011_6: THREE.Mesh
    Curve011_7: THREE.Mesh
    Curve011_8: THREE.Mesh
    Curve011_9: THREE.Mesh
    Curve011_10: THREE.Mesh
    Curve011_11: THREE.Mesh
    Curve011_12: THREE.Mesh
    Curve011_13: THREE.Mesh
    Curve011_14: THREE.Mesh
    Curve011_15: THREE.Mesh
    Curve011_16: THREE.Mesh
    Curve011_17: THREE.Mesh
    Curve011_18: THREE.Mesh
    Curve011_19: THREE.Mesh
    Curve011_20: THREE.Mesh
    Curve011_21: THREE.Mesh
    Curve011_22: THREE.Mesh
    Curve011_23: THREE.Mesh
    Curve011_24: THREE.Mesh
    Curve011_25: THREE.Mesh
    Curve011_26: THREE.Mesh
    Curve011_27: THREE.Mesh
    Curve011_28: THREE.Mesh
    Curve011_29: THREE.Mesh
    Curve011_30: THREE.Mesh
    Curve011_31: THREE.Mesh
    Curve011_32: THREE.Mesh
    Curve011_33: THREE.Mesh
    Curve011_34: THREE.Mesh
    Curve011_35: THREE.Mesh
    Curve011_36: THREE.Mesh
    Curve011_37: THREE.Mesh
    Curve011_38: THREE.Mesh
    Curve011_39: THREE.Mesh
    Curve275: THREE.Mesh
    Curve275_1: THREE.Mesh
    Curve275_2: THREE.Mesh
    Curve005: THREE.Mesh
    Curve281: THREE.Mesh
    Curve281_1: THREE.Mesh
    Curve281_2: THREE.Mesh
    Curve281_3: THREE.Mesh
    Curve281_4: THREE.Mesh
    Curve291: THREE.Mesh
    Curve291_1: THREE.Mesh
    Curve006: THREE.Mesh
    Curve304: THREE.Mesh
    Curve304_1: THREE.Mesh
    Curve010: THREE.Mesh
  }
  materials: {
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['SVGMat.001']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['SVGMat.009']: THREE.MeshStandardMaterial
    ['SVGMat.010']: THREE.MeshStandardMaterial
    ['SVGMat.011']: THREE.MeshStandardMaterial
    ['SVGMat.013']: THREE.MeshStandardMaterial
    ['SVGMat.014']: THREE.MeshStandardMaterial
    ['SVGMat.015']: THREE.MeshStandardMaterial
    ['SVGMat.016']: THREE.MeshStandardMaterial
    ['SVGMat.017']: THREE.MeshStandardMaterial
    ['SVGMat.018']: THREE.MeshStandardMaterial
    ['SVGMat.019']: THREE.MeshStandardMaterial
    ['SVGMat.020']: THREE.MeshStandardMaterial
    ['SVGMat.021']: THREE.MeshStandardMaterial
    ['SVGMat.022']: THREE.MeshStandardMaterial
    ['SVGMat.023']: THREE.MeshStandardMaterial
    ['SVGMat.024']: THREE.MeshStandardMaterial
    ['SVGMat.025']: THREE.MeshStandardMaterial
    ['SVGMat.026']: THREE.MeshStandardMaterial
    ['SVGMat.027']: THREE.MeshStandardMaterial
    ['SVGMat.028']: THREE.MeshStandardMaterial
    ['SVGMat.029']: THREE.MeshStandardMaterial
    ['SVGMat.030']: THREE.MeshStandardMaterial
    ['SVGMat.031']: THREE.MeshStandardMaterial
    ['SVGMat.032']: THREE.MeshStandardMaterial
    ['SVGMat.033']: THREE.MeshStandardMaterial
    ['SVGMat.034']: THREE.MeshStandardMaterial
    ['SVGMat.035']: THREE.MeshStandardMaterial
    ['SVGMat.036']: THREE.MeshStandardMaterial
    ['SVGMat.037']: THREE.MeshStandardMaterial
    ['SVGMat.038']: THREE.MeshStandardMaterial
    ['SVGMat.039']: THREE.MeshStandardMaterial
    ['SVGMat.040']: THREE.MeshStandardMaterial
    ['SVGMat.041']: THREE.MeshStandardMaterial
    ['SVGMat.042']: THREE.MeshStandardMaterial
    ['SVGMat.043']: THREE.MeshStandardMaterial
    ['SVGMat.044']: THREE.MeshStandardMaterial
    ['SVGMat.045']: THREE.MeshStandardMaterial
    ['SVGMat.046']: THREE.MeshStandardMaterial
    ['SVGMat.047']: THREE.MeshStandardMaterial
    ['SVGMat.048']: THREE.MeshStandardMaterial
    ['SVGMat.049']: THREE.MeshStandardMaterial
    ['SVGMat.050']: THREE.MeshStandardMaterial
    ['SVGMat.051']: THREE.MeshStandardMaterial
    ['SVGMat.055']: THREE.MeshStandardMaterial
    ['SVGMat.053']: THREE.MeshStandardMaterial
    ['SVGMat.054']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['SVGMat.060']: THREE.MeshStandardMaterial
    ['SVGMat.058']: THREE.MeshStandardMaterial
    ['SVGMat.059']: THREE.MeshStandardMaterial
    ['SVGMat.061']: THREE.MeshStandardMaterial
    ['SVGMat.062']: THREE.MeshStandardMaterial
    ['SVGMat.066']: THREE.MeshStandardMaterial
    ['SVGMat.068']: THREE.MeshStandardMaterial
    ['SVGMat.075']: THREE.MeshStandardMaterial
    ['SVGMat.077']: THREE.MeshStandardMaterial
    ['SVGMat.078']: THREE.MeshStandardMaterial
    ['SVGMat.079']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Portfolio1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Portfolio1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.shelving.geometry} material={nodes.shelving.material} position={[7.223, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} scale={0.476} />
      <mesh geometry={nodes.body.geometry} material={materials['Material.027']} position={[-1.4, 5.993, 0]} rotation={[0, -1.555, 0]} />
      <mesh geometry={nodes.Face.geometry} material={materials['Material.029']} position={[-1.4, 5.993, 0]} rotation={[0, -1.555, 0]} />
      <mesh geometry={nodes.EM3D_Base_Body.geometry} material={nodes.EM3D_Base_Body.material} position={[0, -0.199, -19.402]} rotation={[1.568, 0.042, 1.633]} scale={0.177} />
      <mesh geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[0.087, 0, 5.324]} scale={0.304} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[6.805, 0.753, -0.41]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.17, -0.026, -0.539]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Material.036']} position={[0.042, 1.857, 7.129]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Material.036']} position={[-1.547, 1.857, 7.08]} rotation={[0, -0.201, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.036']} position={[-3.026, 1.857, 6.808]} rotation={[0, -0.375, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials['Material.036']} position={[-4.501, 1.857, 6.452]} rotation={[0, -0.395, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Material.036']} position={[-5.962, 1.857, 5.961]} rotation={[0, -0.435, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.036']} position={[1.599, 1.857, 7.063]} rotation={[0, 0.038, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Material.036']} position={[3.094, 1.857, 6.843]} rotation={[0, 0.261, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.036']} position={[4.566, 1.857, 6.454]} rotation={[0, 0.357, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.036']} position={[5.984, 1.857, 5.895]} rotation={[0, 0.361, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.036']} position={[-7.661, 1.857, 5.185]} rotation={[0, -0.435, 0]} scale={[0.047, 1.771, 0.263]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0, 0, 7.149]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[7.087, 0.814, -2.041]} rotation={[0, 1.219, 0]} scale={0.206} />
      <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[0, 3.961, 5.686]} scale={0.23} />
      <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[0, 2.043, 5.843]} scale={0.23} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.009']} position={[7.048, 0.664, -1.984]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.014']} position={[7.124, 1.23, -2.215]} rotation={[0, 0.365, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.014']} position={[7.313, 1.238, -0.467]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.002']} position={[-0.019, 0.122, 3.471]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.002']} position={[-2.096, 0.122, -1.017]} rotation={[0, -0.402, 0]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.002']} position={[2.058, 0.122, -1.036]} rotation={[0, 0.402, 0]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.007']} position={[0.044, 1.902, 6.812]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.007']} position={[-1.475, 1.902, 6.749]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.007']} position={[-2.946, 1.902, 6.527]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.007']} position={[-4.401, 1.902, 6.16]} rotation={[0, -0.085, 0]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.007']} position={[-5.801, 1.902, 5.657]} rotation={[0, -0.085, 0]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.007']} position={[1.554, 1.902, 6.767]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.007']} position={[3.049, 1.902, 6.528]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.007']} position={[4.486, 1.902, 6.137]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.007']} position={[5.88, 1.902, 5.587]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.004']} position={[0, 3.69, 7.153]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.037']} position={[0, 1.772, 7.305]} scale={[1.04, 1, 1]} />
      <mesh geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[6.673, 1.153, -2.101]} rotation={[0, -0.245, 0]} scale={0.08} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.022']} position={[7.431, 3.606, -1.007]} rotation={[0.003, 0, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.019']} position={[0, 0.519, 0]} rotation={[0, -0.178, 0]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.021']} position={[0, 0.314, 0]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.020']} position={[0, 0.667, 0]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.015']} position={[7.287, 1.233, -0.466]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.015']} position={[7.083, 1.226, -1.947]} rotation={[-Math.PI, 0.45, Math.PI / 2]} />
      <mesh geometry={nodes.books.geometry} material={materials['Material.034']} position={[7.486, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} />
      <mesh geometry={nodes.Catcus.geometry} material={materials['Material.033']} position={[7.486, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} />
      <mesh geometry={nodes.chair.geometry} material={materials['Material.010']} position={[5.701, 0.224, -0.663]} rotation={[Math.PI, -0.011, Math.PI]} />
      <mesh geometry={nodes.mouse.geometry} material={materials['Material.013']} position={[6.368, 0.013, 1.149]} rotation={[Math.PI, -0.011, Math.PI]} />
      <mesh geometry={nodes.penguin.geometry} material={nodes.penguin.material} position={[6.303, 0.828, -2.613]} rotation={[Math.PI, -1.186, Math.PI]}>
        <mesh geometry={nodes['penguin-wing-0'].geometry} material={nodes['penguin-wing-0'].material} />
        <mesh geometry={nodes['penguin-wing-1'].geometry} material={nodes['penguin-wing-1'].material} />
      </mesh>
      <mesh geometry={nodes.picture.geometry} material={materials['Material.018']} position={[7.638, 2.13, 0.711]} rotation={[Math.PI, -0.011, Math.PI]} />
      <mesh geometry={nodes.picture001.geometry} material={materials['Material.017']} position={[7.621, 2.165, 0.711]} rotation={[Math.PI, -0.011, Math.PI]} />
      <mesh geometry={nodes.plant.geometry} material={materials['Material.016']} position={[6.833, 0.18, 1.463]} rotation={[Math.PI, -0.011, Math.PI]} />
      <mesh geometry={nodes.plant001.geometry} material={materials['Material.011']} position={[6.833, 0.18, 1.463]} rotation={[Math.PI, -0.011, Math.PI]} />
      <mesh geometry={nodes.speaker.geometry} material={nodes.speaker.material} position={[5.844, 0.732, -2.568]} rotation={[0, -1, 0.049]} />
      <mesh geometry={nodes.Table_small.geometry} material={nodes.Table_small.material} position={[7.486, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} />
      <mesh geometry={nodes.Catcus_leaf.geometry} material={materials['Material.032']} position={[7.486, 2.345, -2.989]} rotation={[-1.571, 0.004, 0.011]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.038']} position={[0.087, 1.863, 7.487]} scale={[7.081, 1.809, 0.058]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.Glass} position={[7.692, 1.904, -0.998]} scale={[0.032, 1.856, 6.427]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.005']} position={[0, 0.038, 0.16]} scale={[7.678, 0.029, 7.648]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.003']} position={[0, 0.097, -0.056]} scale={[5.607, 0.067, 5.607]} />
      <mesh geometry={nodes.Face_new.geometry} material={materials['Material.030']} position={[5.777, 1.751, 0.932]} rotation={[1.549, -0.036, -2.124]} />
      <mesh geometry={nodes.Hair.geometry} material={materials['Material.027']} position={[5.725, 0.407, 0.964]} rotation={[-Math.PI, 0.94, -Math.PI]} />
      <mesh geometry={nodes.Hand.geometry} material={materials['Material.026']} position={[5.729, 0.322, 0.961]} rotation={[-Math.PI, 0.94, -Math.PI]} />
      <mesh geometry={nodes.Leg.geometry} material={materials['Material.028']} position={[5.722, 0.322, 0.966]} rotation={[-Math.PI, 0.94, -Math.PI]} />
      <mesh geometry={nodes.Pant.geometry} material={materials['Material.025']} position={[5.722, 0.322, 0.966]} rotation={[-Math.PI, 0.94, -Math.PI]} />
      <mesh geometry={nodes.Shirt.geometry} material={materials['Material.024']} position={[5.722, 0.322, 0.966]} rotation={[-Math.PI, 0.94, -Math.PI]} />
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[3.838, 2.434, 6.611]} rotation={[-1.58, -0.004, 0.434]} />
      <group position={[-2.178, 2.56, 7.079]} rotation={[1.585, 0.001, -3.139]}>
        <mesh geometry={nodes.Curve002_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Curve002_2.geometry} material={materials['Material.023']} />
      </group>
      <mesh geometry={nodes.Curve002.geometry} material={materials['Material.031']} position={[-0.728, 2.526, 7.038]} rotation={[-1.551, 0, 0]} />
      <group position={[-3.833, 2.53, 6.689]} rotation={[1.568, -0.006, -2.725]}>
        <mesh geometry={nodes.Curve008_1.geometry} material={materials['SVGMat.009']} />
        <mesh geometry={nodes.Curve008_2.geometry} material={materials['SVGMat.010']} />
        <mesh geometry={nodes.Curve008_3.geometry} material={materials['SVGMat.011']} />
      </group>
      <group position={[-6.78, 0.804, 5.681]} rotation={[1.571, -0.002, -2.743]}>
        <mesh geometry={nodes.Curve011_1.geometry} material={materials['SVGMat.013']} />
        <mesh geometry={nodes.Curve011_2.geometry} material={materials['SVGMat.014']} />
        <mesh geometry={nodes.Curve011_3.geometry} material={materials['SVGMat.015']} />
        <mesh geometry={nodes.Curve011_4.geometry} material={materials['SVGMat.016']} />
        <mesh geometry={nodes.Curve011_5.geometry} material={materials['SVGMat.017']} />
        <mesh geometry={nodes.Curve011_6.geometry} material={materials['SVGMat.018']} />
        <mesh geometry={nodes.Curve011_7.geometry} material={materials['SVGMat.019']} />
        <mesh geometry={nodes.Curve011_8.geometry} material={materials['SVGMat.020']} />
        <mesh geometry={nodes.Curve011_9.geometry} material={materials['SVGMat.021']} />
        <mesh geometry={nodes.Curve011_10.geometry} material={materials['SVGMat.022']} />
        <mesh geometry={nodes.Curve011_11.geometry} material={materials['SVGMat.023']} />
        <mesh geometry={nodes.Curve011_12.geometry} material={materials['SVGMat.024']} />
        <mesh geometry={nodes.Curve011_13.geometry} material={materials['SVGMat.025']} />
        <mesh geometry={nodes.Curve011_14.geometry} material={materials['SVGMat.026']} />
        <mesh geometry={nodes.Curve011_15.geometry} material={materials['SVGMat.027']} />
        <mesh geometry={nodes.Curve011_16.geometry} material={materials['SVGMat.028']} />
        <mesh geometry={nodes.Curve011_17.geometry} material={materials['SVGMat.029']} />
        <mesh geometry={nodes.Curve011_18.geometry} material={materials['SVGMat.030']} />
        <mesh geometry={nodes.Curve011_19.geometry} material={materials['SVGMat.031']} />
        <mesh geometry={nodes.Curve011_20.geometry} material={materials['SVGMat.032']} />
        <mesh geometry={nodes.Curve011_21.geometry} material={materials['SVGMat.033']} />
        <mesh geometry={nodes.Curve011_22.geometry} material={materials['SVGMat.034']} />
        <mesh geometry={nodes.Curve011_23.geometry} material={materials['SVGMat.035']} />
        <mesh geometry={nodes.Curve011_24.geometry} material={materials['SVGMat.036']} />
        <mesh geometry={nodes.Curve011_25.geometry} material={materials['SVGMat.037']} />
        <mesh geometry={nodes.Curve011_26.geometry} material={materials['SVGMat.038']} />
        <mesh geometry={nodes.Curve011_27.geometry} material={materials['SVGMat.039']} />
        <mesh geometry={nodes.Curve011_28.geometry} material={materials['SVGMat.040']} />
        <mesh geometry={nodes.Curve011_29.geometry} material={materials['SVGMat.041']} />
        <mesh geometry={nodes.Curve011_30.geometry} material={materials['SVGMat.042']} />
        <mesh geometry={nodes.Curve011_31.geometry} material={materials['SVGMat.043']} />
        <mesh geometry={nodes.Curve011_32.geometry} material={materials['SVGMat.044']} />
        <mesh geometry={nodes.Curve011_33.geometry} material={materials['SVGMat.045']} />
        <mesh geometry={nodes.Curve011_34.geometry} material={materials['SVGMat.046']} />
        <mesh geometry={nodes.Curve011_35.geometry} material={materials['SVGMat.047']} />
        <mesh geometry={nodes.Curve011_36.geometry} material={materials['SVGMat.048']} />
        <mesh geometry={nodes.Curve011_37.geometry} material={materials['SVGMat.049']} />
        <mesh geometry={nodes.Curve011_38.geometry} material={materials['SVGMat.050']} />
        <mesh geometry={nodes.Curve011_39.geometry} material={materials['SVGMat.051']} />
      </group>
      <group position={[6.588, 2.439, 5.444]} rotation={[1.58, 0.038, 2.34]}>
        <mesh geometry={nodes.Curve275.geometry} material={materials['SVGMat.055']} />
        <mesh geometry={nodes.Curve275_1.geometry} material={materials['SVGMat.053']} />
        <mesh geometry={nodes.Curve275_2.geometry} material={materials['SVGMat.054']} />
      </group>
      <mesh geometry={nodes.Curve005.geometry} material={materials['Material.035']} position={[5.482, 2.376, 6.267]} rotation={[1.567, 0.006, 2.678]} />
      <group position={[2.334, 2.416, 6.917]} rotation={[1.58, 0.018, 2.792]}>
        <mesh geometry={nodes.Curve281.geometry} material={materials['SVGMat.060']} />
        <mesh geometry={nodes.Curve281_1.geometry} material={materials['SVGMat.058']} />
        <mesh geometry={nodes.Curve281_2.geometry} material={materials['SVGMat.059']} />
        <mesh geometry={nodes.Curve281_3.geometry} material={materials['SVGMat.061']} />
        <mesh geometry={nodes.Curve281_4.geometry} material={materials['SVGMat.062']} />
      </group>
      <group position={[1.02, 2.523, 6.909]} rotation={[1.579, 0.004, 2.995]}>
        <mesh geometry={nodes.Curve291.geometry} material={materials['SVGMat.066']} />
        <mesh geometry={nodes.Curve291_1.geometry} material={materials['SVGMat.068']} />
      </group>
      <mesh geometry={nodes.Curve006.geometry} material={materials['SVGMat.075']} position={[-5.389, 0.781, 6.397]} rotation={[1.551, 0.124, -3.024]} />
      <group position={[-5.215, 2.578, 6.324]} rotation={[1.554, 0.016, -2.878]}>
        <mesh geometry={nodes.Curve304.geometry} material={materials['SVGMat.077']} />
        <mesh geometry={nodes.Curve304_1.geometry} material={materials['SVGMat.078']} />
      </group>
      <mesh geometry={nodes.Curve010.geometry} material={materials['SVGMat.079']} position={[-6.959, 2.883, 5.636]} rotation={[2.068, -0.544, -2.511]} />
    </group>
  )
}

useGLTF.preload('/Portfolio1.glb')
// export default 